<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-H5CHME6" failures="1" tests="1" name="Loginrunner.CucumberRunnerTestslandlordlogin2" time="34.460" errors="0" timestamp="2023-10-24T18:53:35 IST" skipped="0">
  <testcase classname="Loginrunner.CucumberRunnerTestslandlordlogin2" name="runScenario" time="34.460">
    <failure message="The following asserts failed:
	Third soft assert failed expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Third soft assert failed expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at Testcases_original.validate_ScreenshotHooks.Validate(validate_ScreenshotHooks.java:48)
at âœ½.User enters username as 'sayan011981@mailinator.com' and password as 'Mylogin@123'(classpath:feature/test2.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Loginrunner.CucumberRunnerTestslandlordlogin2 -->
